version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17   # You can change to corretto11 or 21 if needed
    commands:
      - echo "Installing Maven dependencies..."
      - mvn clean install -DskipTests=true

  build:
    commands:
      - echo "Building Spring Boot application..."
      - mvn clean package -DskipTests=true
      - echo "Build completed successfully."

  post_build:
    commands:
      - echo "Preparing artifact for deployment..."
      - mkdir -p target/deploy
      - cp target/*.jar target/deploy/
      - cp -r scripts target/deploy/
      - cp appspec.yml target/deploy/
      - echo "Artifact ready."

artifacts:
  files:
    - target/deploy/**/*
  discard-paths: no
